package com.example.demo.horizon.model;

import java.util.Objects;
import com.example.demo.horizon.model.FederalExchangeIndicators;
import com.example.demo.horizon.model.Link;
import com.example.demo.horizon.model.Plan;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;
import org.springframework.validation.annotation.Validated;
import javax.validation.Valid;
import javax.validation.constraints.*;

/**
 * A single member record
 */
@ApiModel(description = "A single member record")
@Validated
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-12-24T01:15:28.003+05:30")

public class MemberElastic   {
  @JsonProperty("memberId")
  private String memberId = null;

  @JsonProperty("personId")
  private String personId = null;

  @JsonProperty("prefix")
  private String prefix = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("middleName")
  private String middleName = null;

  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("suffix")
  private String suffix = null;

  @JsonProperty("dob")
  private LocalDate dob = null;

  @JsonProperty("gender")
  private String gender = null;

  @JsonProperty("ssn")
  private String ssn = null;

  @JsonProperty("medicareBeneficiaryIdentifier")
  private String medicareBeneficiaryIdentifier = null;

  @JsonProperty("medicareNumber")
  private String medicareNumber = null;

  @JsonProperty("horizonEmployeeIndicator")
  private Boolean horizonEmployeeIndicator = null;

  @JsonProperty("federalExchangeIndicators")
  private FederalExchangeIndicators federalExchangeIndicators = null;

  @JsonProperty("disabilityStatus")
  private String disabilityStatus = null;

  @JsonProperty("disabilityEffectiveDate")
  private LocalDate disabilityEffectiveDate = null;

  @JsonProperty("disabilityEndDate")
  private LocalDate disabilityEndDate = null;

  @JsonProperty("links")
  @Valid
  private List<Link> links = null;

  @JsonProperty("plans")
  @Valid
  private List<Plan> plans = null;

  public MemberElastic memberId(String memberId) {
    this.memberId = memberId;
    return this;
  }

  /**
   * Member Id. Unique Member identifier. Note: This is a transient value   This is needed to call other APIs
   * @return memberId
  **/
  @ApiModelProperty(required = true, value = "Member Id. Unique Member identifier. Note: This is a transient value   This is needed to call other APIs")
  @NotNull


  public String getMemberId() {
    return memberId;
  }

  public void setMemberId(String memberId) {
    this.memberId = memberId;
  }

  public MemberElastic personId(String personId) {
    this.personId = personId;
    return this;
  }

  /**
   * **Internal Only:** MDM Original GUID generated by MDM .Its unique at an individual level .
   * @return personId
  **/
  @ApiModelProperty(required = true, value = "**Internal Only:** MDM Original GUID generated by MDM .Its unique at an individual level .")
  @NotNull


  public String getPersonId() {
    return personId;
  }

  public void setPersonId(String personId) {
    this.personId = personId;
  }

  public MemberElastic prefix(String prefix) {
    this.prefix = prefix;
    return this;
  }

  /**
   * Member name prefix
   * @return prefix
  **/
  @ApiModelProperty(value = "Member name prefix")


  public String getPrefix() {
    return prefix;
  }

  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }

  public MemberElastic firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * Member's first name
   * @return firstName
  **/
  @ApiModelProperty(required = true, value = "Member's first name")
  @NotNull


  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public MemberElastic middleName(String middleName) {
    this.middleName = middleName;
    return this;
  }

  /**
   * Member's middle name
   * @return middleName
  **/
  @ApiModelProperty(value = "Member's middle name")


  public String getMiddleName() {
    return middleName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  public MemberElastic lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

  /**
   * Member's last name
   * @return lastName
  **/
  @ApiModelProperty(required = true, value = "Member's last name")
  @NotNull


  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public MemberElastic suffix(String suffix) {
    this.suffix = suffix;
    return this;
  }

  /**
   * Member name suffix
   * @return suffix
  **/
  @ApiModelProperty(value = "Member name suffix")


  public String getSuffix() {
    return suffix;
  }

  public void setSuffix(String suffix) {
    this.suffix = suffix;
  }

  public MemberElastic dob(LocalDate dob) {
    this.dob = dob;
    return this;
  }

  /**
   * Member's Date of Birth. Format  ISO 8601 date in the format yyyy-MM-dd
   * @return dob
  **/
  @ApiModelProperty(required = true, value = "Member's Date of Birth. Format  ISO 8601 date in the format yyyy-MM-dd")
  @NotNull

  @Valid

  public LocalDate getDob() {
    return dob;
  }

  public void setDob(LocalDate dob) {
    this.dob = dob;
  }

  public MemberElastic gender(String gender) {
    this.gender = gender;
    return this;
  }

  /**
   * Member's gender.   Values: * Female * Male * Ambiguous * Not Applicable * Other * Unknown  Note: The API will handle Gender filtration for Male and Female only
   * @return gender
  **/
  @ApiModelProperty(required = true, value = "Member's gender.   Values: * Female * Male * Ambiguous * Not Applicable * Other * Unknown  Note: The API will handle Gender filtration for Male and Female only")
  @NotNull


  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public MemberElastic ssn(String ssn) {
    this.ssn = ssn;
    return this;
  }

  /**
   * **Internal Only:** Member's SSN.   Format nnnnnnnnn.
   * @return ssn
  **/
  @ApiModelProperty(value = "**Internal Only:** Member's SSN.   Format nnnnnnnnn.")


  public String getSsn() {
    return ssn;
  }

  public void setSsn(String ssn) {
    this.ssn = ssn;
  }

  public MemberElastic medicareBeneficiaryIdentifier(String medicareBeneficiaryIdentifier) {
    this.medicareBeneficiaryIdentifier = medicareBeneficiaryIdentifier;
    return this;
  }

  /**
   * **Internal Only:** Medicare Beneficiary Identifier (MBI) This replaces the medicareNumber
   * @return medicareBeneficiaryIdentifier
  **/
  @ApiModelProperty(value = "**Internal Only:** Medicare Beneficiary Identifier (MBI) This replaces the medicareNumber")


  public String getMedicareBeneficiaryIdentifier() {
    return medicareBeneficiaryIdentifier;
  }

  public void setMedicareBeneficiaryIdentifier(String medicareBeneficiaryIdentifier) {
    this.medicareBeneficiaryIdentifier = medicareBeneficiaryIdentifier;
  }

  public MemberElastic medicareNumber(String medicareNumber) {
    this.medicareNumber = medicareNumber;
    return this;
  }

  /**
   * **Internal Only:** Medicare Number. This is legacy Medicare Number comprised of member's SSN and an alphabetic character.
   * @return medicareNumber
  **/
  @ApiModelProperty(value = "**Internal Only:** Medicare Number. This is legacy Medicare Number comprised of member's SSN and an alphabetic character.")


  public String getMedicareNumber() {
    return medicareNumber;
  }

  public void setMedicareNumber(String medicareNumber) {
    this.medicareNumber = medicareNumber;
  }

  public MemberElastic horizonEmployeeIndicator(Boolean horizonEmployeeIndicator) {
    this.horizonEmployeeIndicator = horizonEmployeeIndicator;
    return this;
  }

  /**
   * Indicates if Member is a Horizon employee. Will only be returned when True.
   * @return horizonEmployeeIndicator
  **/
  @ApiModelProperty(value = "Indicates if Member is a Horizon employee. Will only be returned when True.")


  public Boolean isHorizonEmployeeIndicator() {
    return horizonEmployeeIndicator;
  }

  public void setHorizonEmployeeIndicator(Boolean horizonEmployeeIndicator) {
    this.horizonEmployeeIndicator = horizonEmployeeIndicator;
  }

  public MemberElastic federalExchangeIndicators(FederalExchangeIndicators federalExchangeIndicators) {
    this.federalExchangeIndicators = federalExchangeIndicators;
    return this;
  }

  /**
   * Get federalExchangeIndicators
   * @return federalExchangeIndicators
  **/
  @ApiModelProperty(value = "")

  @Valid

  public FederalExchangeIndicators getFederalExchangeIndicators() {
    return federalExchangeIndicators;
  }

  public void setFederalExchangeIndicators(FederalExchangeIndicators federalExchangeIndicators) {
    this.federalExchangeIndicators = federalExchangeIndicators;
  }

  public MemberElastic disabilityStatus(String disabilityStatus) {
    this.disabilityStatus = disabilityStatus;
    return this;
  }

  /**
   * Member's disability status description  Example:  Permanently Handicapped  Temporarily Handicapped
   * @return disabilityStatus
  **/
  @ApiModelProperty(value = "Member's disability status description  Example:  Permanently Handicapped  Temporarily Handicapped")


  public String getDisabilityStatus() {
    return disabilityStatus;
  }

  public void setDisabilityStatus(String disabilityStatus) {
    this.disabilityStatus = disabilityStatus;
  }

  public MemberElastic disabilityEffectiveDate(LocalDate disabilityEffectiveDate) {
    this.disabilityEffectiveDate = disabilityEffectiveDate;
    return this;
  }

  /**
   * Member's disability effective date. Format  ISO 8601 date in the format yyyy-MM-dd
   * @return disabilityEffectiveDate
  **/
  @ApiModelProperty(value = "Member's disability effective date. Format  ISO 8601 date in the format yyyy-MM-dd")

  @Valid

  public LocalDate getDisabilityEffectiveDate() {
    return disabilityEffectiveDate;
  }

  public void setDisabilityEffectiveDate(LocalDate disabilityEffectiveDate) {
    this.disabilityEffectiveDate = disabilityEffectiveDate;
  }

  public MemberElastic disabilityEndDate(LocalDate disabilityEndDate) {
    this.disabilityEndDate = disabilityEndDate;
    return this;
  }

  /**
   * Member's disability end date. Format  ISO 8601 date in the format yyyy-MM-dd
   * @return disabilityEndDate
  **/
  @ApiModelProperty(value = "Member's disability end date. Format  ISO 8601 date in the format yyyy-MM-dd")

  @Valid

  public LocalDate getDisabilityEndDate() {
    return disabilityEndDate;
  }

  public void setDisabilityEndDate(LocalDate disabilityEndDate) {
    this.disabilityEndDate = disabilityEndDate;
  }

  public MemberElastic links(List<Link> links) {
    this.links = links;
    return this;
  }

  public MemberElastic addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<Link>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * Collection of links
   * @return links
  **/
  @ApiModelProperty(value = "Collection of links")

  @Valid

  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public MemberElastic plans(List<Plan> plans) {
    this.plans = plans;
    return this;
  }

  public MemberElastic addPlansItem(Plan plansItem) {
    if (this.plans == null) {
      this.plans = new ArrayList<Plan>();
    }
    this.plans.add(plansItem);
    return this;
  }

  /**
   * Member's home plan information
   * @return plans
  **/
  @ApiModelProperty(value = "Member's home plan information")

  @Valid

  public List<Plan> getPlans() {
    return plans;
  }

  public void setPlans(List<Plan> plans) {
    this.plans = plans;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MemberElastic memberElastic = (MemberElastic) o;
    return Objects.equals(this.memberId, memberElastic.memberId) &&
        Objects.equals(this.personId, memberElastic.personId) &&
        Objects.equals(this.prefix, memberElastic.prefix) &&
        Objects.equals(this.firstName, memberElastic.firstName) &&
        Objects.equals(this.middleName, memberElastic.middleName) &&
        Objects.equals(this.lastName, memberElastic.lastName) &&
        Objects.equals(this.suffix, memberElastic.suffix) &&
        Objects.equals(this.dob, memberElastic.dob) &&
        Objects.equals(this.gender, memberElastic.gender) &&
        Objects.equals(this.ssn, memberElastic.ssn) &&
        Objects.equals(this.medicareBeneficiaryIdentifier, memberElastic.medicareBeneficiaryIdentifier) &&
        Objects.equals(this.medicareNumber, memberElastic.medicareNumber) &&
        Objects.equals(this.horizonEmployeeIndicator, memberElastic.horizonEmployeeIndicator) &&
        Objects.equals(this.federalExchangeIndicators, memberElastic.federalExchangeIndicators) &&
        Objects.equals(this.disabilityStatus, memberElastic.disabilityStatus) &&
        Objects.equals(this.disabilityEffectiveDate, memberElastic.disabilityEffectiveDate) &&
        Objects.equals(this.disabilityEndDate, memberElastic.disabilityEndDate) &&
        Objects.equals(this.links, memberElastic.links) &&
        Objects.equals(this.plans, memberElastic.plans);
  }

  @Override
  public int hashCode() {
    return Objects.hash(memberId, personId, prefix, firstName, middleName, lastName, suffix, dob, gender, ssn, medicareBeneficiaryIdentifier, medicareNumber, horizonEmployeeIndicator, federalExchangeIndicators, disabilityStatus, disabilityEffectiveDate, disabilityEndDate, links, plans);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MemberElastic {\n");
    
    sb.append("    memberId: ").append(toIndentedString(memberId)).append("\n");
    sb.append("    personId: ").append(toIndentedString(personId)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    middleName: ").append(toIndentedString(middleName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    suffix: ").append(toIndentedString(suffix)).append("\n");
    sb.append("    dob: ").append(toIndentedString(dob)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    ssn: ").append(toIndentedString(ssn)).append("\n");
    sb.append("    medicareBeneficiaryIdentifier: ").append(toIndentedString(medicareBeneficiaryIdentifier)).append("\n");
    sb.append("    medicareNumber: ").append(toIndentedString(medicareNumber)).append("\n");
    sb.append("    horizonEmployeeIndicator: ").append(toIndentedString(horizonEmployeeIndicator)).append("\n");
    sb.append("    federalExchangeIndicators: ").append(toIndentedString(federalExchangeIndicators)).append("\n");
    sb.append("    disabilityStatus: ").append(toIndentedString(disabilityStatus)).append("\n");
    sb.append("    disabilityEffectiveDate: ").append(toIndentedString(disabilityEffectiveDate)).append("\n");
    sb.append("    disabilityEndDate: ").append(toIndentedString(disabilityEndDate)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    plans: ").append(toIndentedString(plans)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

